title: My Coding 1 Blog
author: Kataruse
email: pepsiluig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my Blog where I will post updates related to my Coding 1 class for this 2021 semester.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Kataruse # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
